version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: passwd
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://app_user:passwd@db/app_db
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8002:8002"
    depends_on:
      - db
